version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/apps/OJET (VDOM) - OCI Vision/jet_virtual_dom_app"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"

  - package-ecosystem: "npm"
    directory: "/apps/agentic_rag/scripts"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"

  - package-ecosystem: "pip"
    directory: "/apps/langgraph_agent_with_genai/src"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"

  - package-ecosystem: "pip"
    directory: "/workshops/mask_detection_training/infer/files"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"

  - package-ecosystem: "pip"
    directory: "/workshops/neural_networks_hero/infer/files"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
