version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/apps/OJET (VDOM) - OCI Vision/jet_virtual_dom_app"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 1
    groups:
      npm-runtime-minor-patch:
        dependency-type: "production"
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      npm-tooling-minor-patch:
        dependency-type: "development"
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
    labels:
      - "dependencies"

  - package-ecosystem: "npm"
    directory: "/apps/agentic_rag/scripts"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 1
    groups:
      npm-cli-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
    labels:
      - "dependencies"

  - package-ecosystem: "pip"
    directory: "/apps/langgraph_agent_with_genai/src"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 1
    groups:
      python-langgraph-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
    labels:
      - "dependencies"

  - package-ecosystem: "pip"
    directory: "/workshops/mask_detection_training/infer/files"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 1
    groups:
      python-mask-detection-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
    labels:
      - "dependencies"

  - package-ecosystem: "pip"
    directory: "/workshops/neural_networks_hero/infer/files"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 1
    groups:
      python-neural-networks-hero-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
    labels:
      - "dependencies"
